CapaAdministrador/Controllers/DispositivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaAdministrador.Controllers
{
    public class DispositivoController : Controller
    {

        public ActionResult Nuevo()
        {
            return View();
        }

        public ActionResult Eliminar()
        {
            return View();
        }


        // GET: Dispositivo
        public ActionResult Index()
        {
            return View();
        }

        // GET: Dispositivo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Dispositivo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dispositivo/Nuevo

       



        [HttpPost]
        public ActionResult GuardarDispositivo (FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                return View();
        //return RedirectToAction("Nuevo");
    }
            catch
            {
                return View();
}
        }

        // GET: Dispositivo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Dispositivo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dispositivo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dispositivo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CapaAdministrador/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaDatos;
using CapaNegocios;

namespace CapaAdministrador.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarDependencias()
        {
            List<Dependencia> oLista = new List<Dependencia>();

            oLista = new CN_Dependencia().Listar();
                
                

            return Json(new {data = oLista.Where(x=>x.Edificio) } , JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ListarDependenciasDGA()
        {
            List<Dependencia> oLista = new List<Dependencia>();

            oLista = new CN_Dependencia().Listar();



            return Json(new { data = oLista.Where(x =>!x.Edificio) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        } 
        
        public ActionResult DN()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        
        public ActionResult DGA()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult Buscar()
        {
            ViewBag.Message = "Busque su dispositivo";

            return View();
        }
    }
}

CapaAdministrador/Views/Dispositivo/Computadora.cshtml
@{
    ViewBag.Title = "Computadora";
}

<h2>Computadora</h2>

<form action="">
    <!--<label for="tipoDispositivo">Seleccione el tipo de dispositivo:</label>--> @*Traer de la BBDD*@
    <!--<select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="1">Computadora</option>
        <option value="2">Impresora</option>
        <option value="3">Pantalla</option>
        <option value="4">Escaner</option>
        <option value="5">Server</option>
    </select>
    <br><br>

    Seleccione el tipo de dispositivo:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Computadora</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Impresora</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Pantalla</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Escaner</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Server</label>
    <br><br>-->



    <label for="tipoDispositivo">Seleccione el formato del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">formato 1</option>
        <option value="5">formato 2</option>
    </select>
    <br><br>

    <label for="NombreComputadora">N° de Serie:</label>
    <input type="text" id="fname" name="fname"><br><br>

    <label for="NombreComputadora">Nombre de la Computadora:</label>
    <input type="text" id="fname" name="fname"><br><br>

    <label for="tipoDispositivo">Seleccione la marca del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">Marca 1</option>
        <option value="5">Marca 2</option>
    </select>
    <br><br>

    <label for="tipoDispositivo">Seleccione el modelo del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">modelo 1</option>
        <option value="5">modelo 2</option>
    </select>
    <br><br>

    <label for="datemax">Fecha de adquisición:</label>
    <input type="datetime-local" id="datemax" name="datemax" max="1979-12-31"><br><br>


    Estado:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Nuevo</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Usado</label><br>
    <br />

    Comentario/Detalle: <br />
    <textarea id="Detalle" cols="100" rows=8> Ejemplo: Gabinete golpeado en lateral derecho </textarea>
    <br><br>


    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>

    Mother:
    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>

    Microprocesador:
    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>

    Memoria:
    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>

    Disco:
    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>

    Wifi:
    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>








    <input type="submit">
</form>

CapaAdministrador/Views/Dispositivo/Eliminar.cshtml
@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

CapaAdministrador/Views/Dispositivo/Escaner.cshtml
@{
    ViewBag.Title = "Escaner";
}

<h2>Escaner</h2>

<form action="">
    <!--<label for="tipoDispositivo">Seleccione el tipo de dispositivo:</label>--> @*Traer de la BBDD*@
    <!--<select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="1">Computadora</option>
        <option value="2">Impresora</option>
        <option value="3">Pantalla</option>
        <option value="4">Escaner</option>
        <option value="5">Server</option>
    </select>
    <br><br>

    Seleccione el tipo de dispositivo:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Computadora</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Impresora</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Pantalla</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Escaner</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Server</label>
    <br><br>-->



    <label for="tipoDispositivo">Seleccione el formato del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">formato 1</option>
        <option value="5">formato 2</option>
    </select>
    <br><br>

    <label for="NombreComputadora">N° de Serie:</label>
    <input type="text" id="fname" name="fname"><br><br>

    @*<label for="NombreComputadora">Nombre de la Computadora:</label>
        <input type="text" id="fname" name="fname"><br><br>*@

    <label for="tipoDispositivo">Seleccione la marca del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">Marca 1</option>
        <option value="5">Marca 2</option>
    </select>
    <br><br>

    <label for="tipoDispositivo">Seleccione el modelo del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">modelo 1</option>
        <option value="5">modelo 2</option>
    </select>
    <br><br>

    <label for="datemax">Fecha de adquisición:</label>
    <input type="datetime-local" id="datemax" name="datemax" max="1979-12-31"><br><br>


    Estado:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Nuevo</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Usado</label><br>
    <br />

    Comentario/Detalle: <br />
    <textarea id="Detalle" cols="100" rows=8> Ejemplo: Gabinete golpeado en lateral derecho </textarea>
    <br><br>


    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>

    Wifi:
    <label for="tipoDispositivo">datos del wifi:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>





    <input type="submit">
</form>

CapaAdministrador/Views/Dispositivo/Impresora.cshtml
@{
    ViewBag.Title = "Impresora";
}

<h2>Impresora</h2>

<form action="">
    <!--<label for="tipoDispositivo">Seleccione el tipo de dispositivo:</label>--> @*Traer de la BBDD*@
    <!--<select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="1">Computadora</option>
        <option value="2">Impresora</option>
        <option value="3">Pantalla</option>
        <option value="4">Escaner</option>
        <option value="5">Server</option>
    </select>
    <br><br>

    Seleccione el tipo de dispositivo:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Computadora</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Impresora</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Pantalla</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Escaner</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Server</label>
    <br><br>-->



    <label for="tipoDispositivo">Seleccione el formato del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">formato 1</option>
        <option value="5">formato 2</option>
    </select>
    <br><br>

    <label for="NombreComputadora">N° de Serie:</label>
    <input type="text" id="fname" name="fname"><br><br>

    @*<label for="NombreComputadora">Nombre de la Computadora:</label>
        <input type="text" id="fname" name="fname"><br><br>*@

    <label for="tipoDispositivo">Seleccione la marca del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">Marca 1</option>
        <option value="5">Marca 2</option>
    </select>
    <br><br>

    <label for="tipoDispositivo">Seleccione el modelo del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">modelo 1</option>
        <option value="5">modelo 2</option>
    </select>
    <br><br>

    <label for="datemax">Fecha de adquisición:</label>
    <input type="datetime-local" id="datemax" name="datemax" max="1979-12-31"><br><br>


    Estado:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Nuevo</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Usado</label><br>
    <br />

    Comentario/Detalle: <br />
    <textarea id="Detalle" cols="100" rows=8> Ejemplo: Gabinete golpeado en lateral derecho </textarea>
    <br><br>


    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>

    Wifi:
    <label for="tipoDispositivo">Datos del wifi:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>





    <input type="submit">
</form>

CapaAdministrador/Views/Dispositivo/Nuevo.cshtml
@{
    ViewBag.Title = "Nuevo";
}


<h2>Nuevo Dispositivo</h2>

<form action="">
    <label for="tipoDispositivo">Seleccione el tipo de dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="1">Computadora</option>
        <option value="2">Impresora</option>
        <option value="3">Pantalla</option>
        <option value="4">Escaner</option>
        <option value="5">Server</option>
    </select>
    <br><br>

    Seleccione el tipo de dispositivo:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Computadora</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Impresora</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Pantalla</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Escaner</label>
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Server</label>
    <br><br>



    <label for="tipoDispositivo">Seleccione el formato del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">formato 1</option>
        <option value="5">formato 2</option>
    </select>
    <br><br>

    <label for="NombreComputadora">N° de Serie:</label>
    <input type="text" id="fname" name="fname"><br><br>

    <label for="NombreComputadora">Nombre de la Computadora:</label>
    <input type="text" id="fname" name="fname"><br><br>

    <label for="tipoDispositivo">Seleccione la marca del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">Marca 1</option>
        <option value="5">Marca 2</option>
    </select>
    <br><br>

    <label for="tipoDispositivo">Seleccione el modelo del dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">modelo 1</option>
        <option value="5">modelo 2</option>
    </select>
    <br><br>

    <label for="datemax">Fecha de adquisición:</label>
    <input type="datetime-local" id="datemax" name="datemax" max="1979-12-31"><br><br>


    Estado:
    <input type="radio" id="html" name="fav_language" value="HTML">
    <label for="1">Nuevo</label>
    <input type="radio" id="css" name="fav_language" value="CSS">
    <label for="0">Usado</label><br>
    <br />

    Comentario/Detalle: <br />
        <textarea id="Detalle" cols="100" rows=8 > Ejemplo: Gabinete golpeado en lateral derecho </textarea>
    <br><br>


    <label for="tipoDispositivo">Seleccione la dependencia a la que pertenece el dispositivo:</label> @*Traer de la BBDD*@
    <select id="tipoDispositivo" name="comboNuevoDispositivo">
        <option value="4">dependencia 1</option>
        <option value="5">dependencia 2</option>
    </select>
    <br><br>







    <input type="submit">
</form>

CapaAdministrador/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>USarlanga</p>
</main>

CapaAdministrador/Views/Home/Buscar.cshtml
@{
    ViewBag.Title = "Buscar";
}

<h2>Buscar</h2>

CapaAdministrador/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

CapaAdministrador/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - S.I.P.I.</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" @Html.ActionLink("S.I.P.I.", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Buscar..." aria-label="Buscar..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Opciones</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar Sesión</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">

                        <a class="nav-link" href="@Url.Action("Index","Home")" @*"/Home/Index"*@ data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                            Inicio
                            <div class="sb-sidenav-collapse-arrow"></div>
                        </a>


                        <a class="nav-link" href="@Url.Action("DN","Home")" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-building"></i></div>
                            DN
                            <div class="sb-sidenav-collapse-arrow"></div>
                        </a>

                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>
                        <a class="nav-link" href="@Url.Action("DGA","Home")" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-building"></i></div>
                            DGA
                            <div class="sb-sidenav-collapse-arrow"></div>
                        </a>

                        <div class="sb-sidenav-menu-heading">BASE DE DATOS</div>


                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-plus-circle"></i></div>
                            Nuevo Dispositivo
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>

                        @*<a class="nav-link" href="@Url.Action("Nuevo","Dispositivo")" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
            <div class="sb-nav-link-icon"><i class="fas fa-plus-circle"></i></div>
            Nuevo Dispositivo
        </a>*@
                        <a class="nav-link" href="@Url.Action("Eliminar","Dispositivo")" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-minus-circle"></i></div>
                            Baja de Dispositivo
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Usuario
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Servicio Penitenciario Federal 2024</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    @*  <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>